### PR TITLE
Add sound effects to the game

### PR DESCRIPTION
**Pull request by mrnakumar**
Play sound when:
* snake eats an apple
* game over

To play without sound, command line flag --silent should be passed.

### CODE REVIEW

**Comment by mrnakumar** [comment]
@liweiyi88

**Comment by liweiyi88** [comment]
@mrnakumar thanks for your PR, it looks cool!
I would make 2 suggestions based on the PR.
1. Let's use the standard package `embed`  to load the static file at compile time. Thus we do not need to pass the path argument to load the file at runtime. What you can do is basically create a file in the assets folder and export a var like the below snippet (`assets/embed.go`)
```
package assets

import "embed"

//go:embed *
var Assets embed.FS
```

Then use `assets.Assets` as the normal file to read the mp3. e.g.
```
f, err := assets.Assets.Open(filename)
	if err != nil {
		return nil, beep.Format{}, err
	}
```

2. It would be better to add a command option (`--silent`) to mute the background music. Afterall, there are some time when people want to play the game without any background sounds.

Please let me know your thoughts.

**Comment by mrnakumar** [comment]
@liweiyi88 thanks for comments. I have made changes accordingly. Please let me know if this is okay.

**Comment by liweiyi88** [comment]
@mrnakumar Well done 🎉

**Pull request merged**
